name: Build affected 2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install
        run: npm install

      - name: lint
        run: npx nx affected:lint

      - name: build
        run: npx nx affected:build
